defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: fgoats_development

test:
  <<: *defaults
  database: fgoats_test

# set these environment variables on your prod server
production:
  database: fgoats
  uri: <%= ENV['MONGOHQ_URL'] || 'mongodb://localhost/sushi' %>
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
